import { Inter } from "next/font/google";
import '../styles/globals.css'
import Nav from "../components/Nav";
import Provider from "../components/Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          <main className="">
            <Nav />
            {children}
          </main>

          <div className="w-full h-full fixed top-0 z-[-10]">
            <div className="gradient" />
          </div>
        </Provider>
      </body>
    </html>
  );
}